apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-deployment
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: 539935451710.dkr.ecr.us-east-1.amazonaws.com/hackathon-adrija-repo:latest
        ports:
        - containerPort: 3001
        env:
        - name: SERVICE
          value: "appointment"

